version: '3.8'

services:

  mysql:
    image: "mysql:latest"
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: siga_bem_db
      MYSQL_USER: siga_bem_user
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQN

#docker-compose up -d