CREATE TABLE funcionario
(
    id                   BIGINT       NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome                 VARCHAR(255) NOT NULL,
    apelido_segundo_nome VARCHAR(255),
    cpf                  VARCHAR(11)  NOT NULL,
    rg                   VARCHAR(10),
    nascimento           varchar(8),
    carteira_trabalho    varchar(11),
    pis                  VARCHAR(11),
    cnh                  VARCHAR(11),
    cnh_cat              VARCHAR(1),
    cnh_vencimento       VARCHAR(8),
    estado_civil         VARCHAR(20),
    nome_conjuge         VARCHAR(255),
    n_depend             INT,
    moradia              VARCHAR(150),
    logradouro           VARCHAR(600),
    complemento          VARCHAR(600),
    bairro               VARCHAR(255),
    numero               INT,
    uf                   VARCHAR(2),
    cidade               VARCHAR(255),
    cep                  VARCHAR(8),
    telefone             VARCHAR(30),
    celular              VARCHAR(30),
    email                VARCHAR(255),
    naturalidade         VARCHAR(50) DEFAULT 'Brasileira',
    escolaridade         VARCHAR(100),
    id_fornecedor        BIGINT       NOT NULL,
    FOREIGN KEY (id_fornecedor) REFERENCES fornecedor (id),
    createdAt      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updateAt       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)